name: Build and install

on:
  # pull_request:
  # push:
    # branches: [main]
  workflow_dispatch:
  workflow_call:
    # inputs:
    #   workflow_id:
    #     required: true
    #     type: string
    #   workflow_file:
    #     required: true
    #     type: string
    #   workflow_input: {}
    #   workflow_input_required: false

jobs:
  build_and_install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Build and install dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd:
            make install