name: Lint

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Build and install dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd:
            make install
            
      - name: Lint files
        uses: devcontainers/ci@v0.3
        with:
          runCmd:
            make lint