name: Tests

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repository content
      #   uses: actions/checkout@v4

      # - name: Build and install dev container
      #   uses: devcontainers/ci@v0.3
      #   with:
      #     runCmd:
      #       make install
            
      - name: Build image
        uses: ./.github/workflows/build.yaml
      
      - name: Test packages
        uses: devcontainers/ci@v0.3
        with:
          runCmd:
            make test